sonar.projectKey=williamkreese21
sonar.organization=williamkreese21
sonar.projectName=William Kreese Web Platform
sonar.sources=src
sonar.exclusions=dist/**,node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8